import {
  RefreshCw, Sparkles, Plus, Trash2, Eye, Download, Printer, Mail, MessageSquare
} from "lucide-react";

export default function AdminInvoiceForm({
  activeTab,
  form,
  setForm,
  generateNewUniqueInvoice,
  updateItem,
  addItem,
  removeItem,
  computedAmountInWords,
  subTotal,
  totalTax,
  totalPayable,
  termsTextareaRef,
  onGenerate,
  onDownloadPDF,
  onPrint,
  onSendEmail,
  onSendWhatsApp,
  onReset,
}) {
  return (
    <div className={activeTab === "generator" ? "no-print space-y-6" : "hidden no-print"}>
      {/* Top Title Card */}
      <div className="flex flex-wrap items-center justify-between gap-4 rounded-3xl border border-amber-900/15 bg-white p-6 text-stone-900 shadow-xl shadow-stone-200/50">
        <div className="flex items-center gap-3.5">
          <img src="/Web.jpeg" alt="Lekhok" className="h-11 w-11 object-contain rounded-xl border border-amber-200 p-0.5" />
          <div>
            <h2 className="text-lg font-black tracking-wider uppercase text-amber-950">
              LEKHOK TRIPURA PUBLISHERS
            </h2>
            <p className="text-xs font-bold text-[#8B5E3C] uppercase tracking-widest">
              INVOICE GENERATOR
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={onReset}
            className="flex items-center gap-1.5 rounded-xl border border-stone-300 bg-[#F7F3ED] px-4 py-2 text-xs font-bold text-stone-800 hover:bg-stone-200 transition"
          >
            <RefreshCw className="h-3.5 w-3.5" /> Reset Form
          </button>
        </div>
      </div>

      {/* SECTION 1: BILL INFORMATION */}
      <div className="rounded-3xl border border-amber-900/15 bg-white p-6 text-stone-900 shadow-xl shadow-stone-200/50">
        <h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-amber-950 border-b border-stone-200 pb-3 flex items-center gap-2">
          <span className="h-2.5 w-2.5 rounded-full bg-amber-700" /> 1. BILL INFORMATION
        </h3>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <div>
            <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
              Bill Generated By
            </label>
            <input
              type="text"
              value={form.billInfo.generatedBy}
              onChange={(e) =>
                setForm({
                  ...form,
                  billInfo: { ...form.billInfo, generatedBy: e.target.value },
                })
              }
              className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
            />
          </div>
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Invoice No. *
              </label>
              <button
                type="button"
                onClick={() => generateNewUniqueInvoice(true)}
                title="Generate Next Unique Invoice No."
                className="flex items-center gap-1 text-[10px] font-bold text-[#8B5E3C] hover:text-amber-900 transition"
              >
                <Sparkles className="h-3 w-3" /> Auto-Generate
              </button>
            </div>
            <div className="relative flex items-center">
              <input
                type="text"
                value={form.billInfo.invoiceNo}
                onChange={(e) =>
                  setForm({
                    ...form,
                    billInfo: { ...form.billInfo, invoiceNo: e.target.value },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-black text-[#6B4226] tracking-wider focus:border-amber-700 focus:outline-none transition pr-9 font-mono"
              />
              <button
                type="button"
                onClick={() => generateNewUniqueInvoice(true)}
                className="absolute right-2.5 text-stone-500 hover:text-amber-900 p-1 rounded-lg transition"
                title="Click to generate next unique sequence"
              >
                <RefreshCw className="h-3.5 w-3.5" />
              </button>
            </div>
          </div>
          <div>
            <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
              Billing Date
            </label>
            <input
              type="date"
              value={form.billInfo.billingDate}
              onChange={(e) =>
                setForm({
                  ...form,
                  billInfo: { ...form.billInfo, billingDate: e.target.value },
                })
              }
              className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
            />
          </div>
          <div>
            <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
              Payment Mode
            </label>
            <select
              value={form.billInfo.paymentMode}
              onChange={(e) =>
                setForm({
                  ...form,
                  billInfo: { ...form.billInfo, paymentMode: e.target.value },
                })
              }
              className="w-full rounded-xl border border-stone-300 bg-white px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
            >
              <option value="Google Pay">Google Pay</option>
              <option value="PhonePe">PhonePe</option>
              <option value="Paytm">Paytm</option>
              <option value="UPI">UPI</option>
              <option value="Bank Transfer">Bank Transfer</option>
              <option value="Cash">Cash</option>
              <option value="Razorpay">Razorpay</option>
            </select>
          </div>
        </div>
      </div>

      {/* SECTIONS 2, 3, 4: BILL TO, SHIP TO, DELIVERY DETAILS */}
      <div className="grid gap-6 lg:grid-cols-3">
        {/* 2. BILL TO */}
        <div className="rounded-3xl border border-amber-900/15 bg-white p-6 text-stone-900 shadow-xl shadow-stone-200/50">
          <h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-amber-950 border-b border-stone-200 pb-3 flex items-center gap-2">
            <span className="h-2.5 w-2.5 rounded-full bg-amber-700" /> 2. BILL TO
          </h3>
          <div className="space-y-3.5">
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Name *
              </label>
              <input
                type="text"
                value={form.billTo.name}
                onChange={(e) =>
                  setForm({
                    ...form,
                    billTo: { ...form.billTo, name: e.target.value },
                  })
                }
                placeholder="Enter customer full name"
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Address *
              </label>
              <textarea
                rows={2}
                value={form.billTo.address}
                onChange={(e) =>
                  setForm({
                    ...form,
                    billTo: { ...form.billTo, address: e.target.value },
                  })
                }
                placeholder="Enter street, city, pincode"
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                State
              </label>
              <input
                type="text"
                value={form.billTo.state}
                onChange={(e) =>
                  setForm({
                    ...form,
                    billTo: { ...form.billTo, state: e.target.value },
                  })
                }
                placeholder="Tripura"
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                GST No.
              </label>
              <input
                type="text"
                value={form.billTo.gstNo}
                onChange={(e) =>
                  setForm({
                    ...form,
                    billTo: { ...form.billTo, gstNo: e.target.value },
                  })
                }
                placeholder="NA or GST Number"
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Phone No. (10 Digits)
              </label>
              <input
                type="tel"
                maxLength={10}
                value={form.billTo.phoneNo}
                onChange={(e) => {
                  const cleaned = e.target.value.replace(/[^0-9]/g, "").slice(0, 10);
                  setForm({
                    ...form,
                    billTo: { ...form.billTo, phoneNo: cleaned },
                  });
                }}
                placeholder="Enter 10-digit mobile number"
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition font-mono"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Mail ID
              </label>
              <input
                type="email"
                value={form.billTo.email}
                onChange={(e) =>
                  setForm({
                    ...form,
                    billTo: { ...form.billTo, email: e.target.value },
                  })
                }
                placeholder="customer@example.com"
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
          </div>
        </div>

        {/* 3. SHIP TO */}
        <div className="rounded-3xl border border-amber-900/15 bg-white p-6 text-stone-900 shadow-xl shadow-stone-200/50">
          <div className="mb-4 flex items-center justify-between border-b border-stone-200 pb-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-amber-950 flex items-center gap-2">
              <span className="h-2.5 w-2.5 rounded-full bg-amber-700" /> 3. SHIP TO
            </h3>
            <label className="flex items-center gap-1.5 text-xs text-stone-700 font-medium cursor-pointer">
              <input
                type="checkbox"
                checked={form.shipTo.sameAsBillTo}
                onChange={(e) =>
                  setForm({
                    ...form,
                    shipTo: { ...form.shipTo, sameAsBillTo: e.target.checked },
                  })
                }
                className="rounded border-stone-300 text-amber-700 focus:ring-0"
              />
              Same as Bill To
            </label>
          </div>
          <div className="space-y-3.5">
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Name
              </label>
              <input
                type="text"
                disabled={form.shipTo.sameAsBillTo}
                value={form.shipTo.name}
                onChange={(e) =>
                  setForm({
                    ...form,
                    shipTo: { ...form.shipTo, name: e.target.value },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 disabled:opacity-50 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Address
              </label>
              <textarea
                rows={2}
                disabled={form.shipTo.sameAsBillTo}
                value={form.shipTo.address}
                onChange={(e) =>
                  setForm({
                    ...form,
                    shipTo: { ...form.shipTo, address: e.target.value },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 disabled:opacity-50 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                State
              </label>
              <input
                type="text"
                disabled={form.shipTo.sameAsBillTo}
                value={form.shipTo.state}
                onChange={(e) =>
                  setForm({
                    ...form,
                    shipTo: { ...form.shipTo, state: e.target.value },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 disabled:opacity-50 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                GST No.
              </label>
              <input
                type="text"
                disabled={form.shipTo.sameAsBillTo}
                value={form.shipTo.gstNo}
                onChange={(e) =>
                  setForm({
                    ...form,
                    shipTo: { ...form.shipTo, gstNo: e.target.value },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 disabled:opacity-50 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
          </div>
        </div>

        {/* 4. DELIVERY DETAILS */}
        <div className="rounded-3xl border border-amber-900/15 bg-white p-6 text-stone-900 shadow-xl shadow-stone-200/50">
          <h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-amber-950 border-b border-stone-200 pb-3 flex items-center gap-2">
            <span className="h-2.5 w-2.5 rounded-full bg-amber-700" /> 4. DELIVERY DETAILS
          </h3>
          <div className="space-y-3.5">
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Delivery Charges (₹)
              </label>
              <input
                type="text"
                inputMode="decimal"
                value={
                  form.deliveryDetails.deliveryCharges === 0 ||
                  form.deliveryDetails.deliveryCharges === "0"
                    ? ""
                    : form.deliveryDetails.deliveryCharges
                }
                onFocus={(e) => e.target.select()}
                onChange={(e) => {
                  const val = e.target.value.replace(/[^0-9.]/g, "");
                  setForm({
                    ...form,
                    deliveryDetails: {
                      ...form.deliveryDetails,
                      deliveryCharges: val,
                    },
                  });
                }}
                placeholder="0"
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition font-mono"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Courier Name
              </label>
              <input
                type="text"
                value={form.deliveryDetails.courierName}
                onChange={(e) =>
                  setForm({
                    ...form,
                    deliveryDetails: {
                      ...form.deliveryDetails,
                      courierName: e.target.value,
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Courier ID / AWB
              </label>
              <input
                type="text"
                value={form.deliveryDetails.courierId}
                onChange={(e) =>
                  setForm({
                    ...form,
                    deliveryDetails: {
                      ...form.deliveryDetails,
                      courierId: e.target.value,
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
          </div>
        </div>
      </div>

      {/* SECTION 5: GOODS & SERVICES (ITEMIZED TABLE) */}
      <div className="rounded-3xl border border-amber-900/15 bg-white p-6 text-stone-900 shadow-xl shadow-stone-200/50">
        <div className="flex items-center justify-between mb-4 border-b border-stone-200 pb-3">
          <h3 className="text-xs font-bold uppercase tracking-wider text-amber-950 flex items-center gap-2">
            <span className="h-2.5 w-2.5 rounded-full bg-amber-700" /> 5. GOODS & SERVICES
          </h3>
          <button
            onClick={addItem}
            className="flex items-center gap-1.5 rounded-xl bg-[#6B4226] px-3 py-1.5 text-xs font-bold text-white hover:bg-[#52331C] transition shadow-md"
          >
            <Plus className="h-4 w-4" /> Add Item
          </button>
        </div>

        <div className="overflow-x-auto rounded-2xl border border-amber-900/15">
          <table className="w-full border-collapse text-xs">
            <thead>
              <tr className="bg-[#3B2314] text-amber-100 text-left font-bold uppercase text-[10px]">
                <th className="p-3 w-12 text-center">#</th>
                <th className="p-3">DESCRIPTION</th>
                <th className="p-3 w-32">HSN/SAC</th>
                <th className="p-3 w-24 text-center">QTY</th>
                <th className="p-3 w-32 text-right">RATE (₹)</th>
                <th className="p-3 w-36 text-right">AMOUNT (₹)</th>
                <th className="p-3 w-12 text-center"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-stone-200">
              {form.items.map((item, index) => (
                <tr key={item.id} className="hover:bg-amber-50/60 transition">
                  <td className="p-3 text-center font-bold text-stone-500">{index + 1}</td>
                  <td className="p-3">
                    <input
                      type="text"
                      value={item.description}
                      onChange={(e) => updateItem(item.id, "description", e.target.value)}
                      placeholder="e.g. Publishing Services"
                      className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3 py-2 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
                    />
                  </td>
                  <td className="p-3">
                    <input
                      type="text"
                      value={item.hsn}
                      onChange={(e) => updateItem(item.id, "hsn", e.target.value)}
                      placeholder="998313"
                      className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3 py-2 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
                    />
                  </td>
                  <td className="p-3 text-center">
                    <input
                      type="text"
                      inputMode="numeric"
                      value={item.qty === 0 || item.qty === "0" ? "" : item.qty}
                      onFocus={(e) => e.target.select()}
                      onChange={(e) => {
                        const val = e.target.value.replace(/[^0-9]/g, "");
                        updateItem(item.id, "qty", val);
                      }}
                      placeholder="0"
                      className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3 py-2 text-center text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition font-mono"
                    />
                  </td>
                  <td className="p-3 text-right">
                    <input
                      type="text"
                      inputMode="decimal"
                      value={item.rate === 0 || item.rate === "0" ? "" : item.rate}
                      onFocus={(e) => e.target.select()}
                      onChange={(e) => {
                        const val = e.target.value.replace(/[^0-9.]/g, "");
                        updateItem(item.id, "rate", val);
                      }}
                      placeholder="0.00"
                      className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3 py-2 text-right text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition font-mono"
                    />
                  </td>
                  <td className="p-3 text-right font-black text-emerald-700 text-sm">
                    ₹{item.amount.toFixed(2)}
                  </td>
                  <td className="p-3 text-center">
                    {form.items.length > 1 && (
                      <button
                        onClick={() => removeItem(item.id)}
                        className="text-rose-600 hover:text-rose-800 p-1.5 rounded-lg hover:bg-rose-100 transition"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Amount in words */}
        <div className="mt-5 pt-4 border-t border-stone-200">
          <div className="flex items-center justify-between mb-1.5">
            <label className="text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
              Amount in Words
            </label>
            <span className="text-[10px] font-bold text-amber-900 bg-amber-100 border border-amber-300 px-2 py-0.5 rounded-md">
              Auto-Typed from Total Payable (₹{totalPayable.toFixed(2)})
            </span>
          </div>
          <input
            type="text"
            value={computedAmountInWords}
            onChange={(e) => setForm({ ...form, customAmountInWords: e.target.value })}
            placeholder="Amount in words will be automatically typed based on total payable amount..."
            className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-4 py-3 text-xs font-bold text-amber-950 focus:border-amber-700 focus:outline-none transition"
          />
          {totalTax > 0 ? (
            <p className="mt-1.5 text-[10px] text-stone-600 font-medium flex items-center gap-1.5">
              <span>💡</span> Includes ₹{subTotal.toFixed(2)} Subtotal + ₹{totalTax.toFixed(2)} GST (
              {form.taxConfig.cgstRate + form.taxConfig.sgstRate}%) = ₹{totalPayable.toFixed(2)} Total Payable
            </p>
          ) : (
            <p className="mt-1.5 text-[10px] text-stone-600 font-medium">
              💡 Total Payable: ₹{totalPayable.toFixed(2)} (No tax added)
            </p>
          )}
        </div>
      </div>

      {/* SECTIONS 6 & 7: BANK DETAILS & TAX SUMMARY */}
      <div className="grid gap-6 lg:grid-cols-2">
        {/* 6. BANK DETAILS */}
        <div className="rounded-3xl border border-amber-900/15 bg-white p-6 text-stone-900 shadow-xl shadow-stone-200/50">
          <h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-amber-950 border-b border-stone-200 pb-3 flex items-center gap-2">
            <span className="h-2.5 w-2.5 rounded-full bg-amber-700" /> 6. BANK DETAILS
          </h3>
          <div className="grid gap-3.5 sm:grid-cols-2">
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Account Name
              </label>
              <input
                type="text"
                value={form.bankDetails.accountName}
                onChange={(e) =>
                  setForm({
                    ...form,
                    bankDetails: {
                      ...form.bankDetails,
                      accountName: e.target.value.toUpperCase(),
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium uppercase text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Account No.
              </label>
              <input
                type="text"
                value={form.bankDetails.accountNo}
                onChange={(e) =>
                  setForm({
                    ...form,
                    bankDetails: {
                      ...form.bankDetails,
                      accountNo: e.target.value.toUpperCase(),
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium uppercase text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                IFSC Code
              </label>
              <input
                type="text"
                value={form.bankDetails.ifscCode}
                onChange={(e) =>
                  setForm({
                    ...form,
                    bankDetails: {
                      ...form.bankDetails,
                      ifscCode: e.target.value.toUpperCase(),
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium uppercase text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Branch Code
              </label>
              <input
                type="text"
                value={form.bankDetails.branchCode}
                onChange={(e) =>
                  setForm({
                    ...form,
                    bankDetails: {
                      ...form.bankDetails,
                      branchCode: e.target.value.toUpperCase(),
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium uppercase text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                CIF
              </label>
              <input
                type="text"
                value={form.bankDetails.cif}
                onChange={(e) =>
                  setForm({
                    ...form,
                    bankDetails: {
                      ...form.bankDetails,
                      cif: e.target.value.toUpperCase(),
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium uppercase text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                MICR
              </label>
              <input
                type="text"
                value={form.bankDetails.micr}
                onChange={(e) =>
                  setForm({
                    ...form,
                    bankDetails: {
                      ...form.bankDetails,
                      micr: e.target.value.toUpperCase(),
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium uppercase text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div className="sm:col-span-2">
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                UPI ID
              </label>
              <input
                type="text"
                value={form.bankDetails.upiId}
                onChange={(e) =>
                  setForm({
                    ...form,
                    bankDetails: {
                      ...form.bankDetails,
                      upiId: e.target.value.toUpperCase(),
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium uppercase text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
          </div>
        </div>

        {/* 7. TAX & CHARGES CONFIGURATION */}
        <div className="rounded-3xl border border-amber-900/15 bg-white p-6 text-stone-900 shadow-xl shadow-stone-200/50">
          <h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-amber-950 border-b border-stone-200 pb-3 flex items-center gap-2">
            <span className="h-2.5 w-2.5 rounded-full bg-amber-700" /> 7. TAX & CHARGES CONFIG
          </h3>
          <div className="grid gap-3.5 sm:grid-cols-2">
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                CGST Rate (%)
              </label>
              <input
                type="number"
                step="0.1"
                value={form.taxConfig.cgstRate}
                onChange={(e) =>
                  setForm({
                    ...form,
                    taxConfig: {
                      ...form.taxConfig,
                      cgstRate: Number(e.target.value) || 0,
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                SGST Rate (%)
              </label>
              <input
                type="number"
                step="0.1"
                value={form.taxConfig.sgstRate}
                onChange={(e) =>
                  setForm({
                    ...form,
                    taxConfig: {
                      ...form.taxConfig,
                      sgstRate: Number(e.target.value) || 0,
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Packaging Charge (₹)
              </label>
              <input
                type="number"
                value={form.extraCharges.packagingCharge}
                onChange={(e) =>
                  setForm({
                    ...form,
                    extraCharges: {
                      ...form.extraCharges,
                      packagingCharge: Number(e.target.value) || 0,
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Courier Charge (₹)
              </label>
              <input
                type="number"
                value={form.extraCharges.courierCharge}
                onChange={(e) =>
                  setForm({
                    ...form,
                    extraCharges: {
                      ...form.extraCharges,
                      courierCharge: Number(e.target.value) || 0,
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Platform Charge (₹)
              </label>
              <input
                type="number"
                value={form.extraCharges.platformCharge}
                onChange={(e) =>
                  setForm({
                    ...form,
                    extraCharges: {
                      ...form.extraCharges,
                      platformCharge: Number(e.target.value) || 0,
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-medium text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Discount Amount (₹)
              </label>
              <input
                type="number"
                value={form.extraCharges.discountAmount}
                onChange={(e) =>
                  setForm({
                    ...form,
                    extraCharges: {
                      ...form.extraCharges,
                      discountAmount: Number(e.target.value) || 0,
                    },
                  })
                }
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-bold text-amber-950 focus:border-amber-700 focus:outline-none transition"
              />
            </div>
          </div>
        </div>
      </div>

      {/* SECTION 8: TERMS & CONDITIONS & SIGNATORY CONFIG */}
      <div className="rounded-3xl border border-amber-900/15 bg-white p-6 text-stone-900 shadow-xl shadow-stone-200/50">
        <h3 className="mb-4 text-xs font-bold uppercase tracking-wider text-amber-950 border-b border-stone-200 pb-3 flex items-center gap-2">
          <span className="h-2.5 w-2.5 rounded-full bg-amber-700" /> 8. TERMS & SIGNATURE STAMP
        </h3>
        <div className="grid gap-6 lg:grid-cols-2">
          <div>
            <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
              Terms & Conditions
            </label>
            <textarea
              ref={termsTextareaRef}
              rows={5}
              value={form.terms}
              onChange={(e) => setForm({ ...form, terms: e.target.value })}
              className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] p-3.5 text-xs font-medium text-stone-900 leading-relaxed focus:border-amber-700 focus:outline-none transition overflow-y-auto max-h-[160px]"
            />
          </div>

          <div className="space-y-4">
            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Authorised Signatory Name
              </label>
              <input
                type="text"
                value={form.signatoryName}
                onChange={(e) => setForm({ ...form, signatoryName: e.target.value })}
                className="w-full rounded-xl border border-stone-300 bg-[#F7F3ED] px-3.5 py-2.5 text-xs font-bold text-stone-900 focus:border-amber-700 focus:outline-none transition"
              />
            </div>

            <div>
              <label className="mb-1.5 block text-[10px] sm:text-xs font-semibold uppercase tracking-wider text-stone-600">
                Website Redirection QR Code
              </label>
              <div className="flex items-center gap-4 rounded-2xl border border-stone-300 bg-[#F7F3ED] p-4">
                <img
                  src="/lekhoktripura_qr.png"
                  alt="Website QR Code"
                  className="h-16 w-16 object-contain rounded-xl border border-stone-300 bg-white p-1.5 shadow-sm shrink-0"
                />
                <div className="text-xs text-stone-600">
                  <p className="font-bold text-stone-900 flex items-center gap-1.5">
                    <span>Scan to Visit Website</span>
                    <span className="text-[10px] font-bold text-amber-900 bg-amber-100 border border-amber-300 px-2 py-0.5 rounded-md">
                      Scannable
                    </span>
                  </p>
                  <a
                    href="https://www.lekhoktripura.in/"
                    target="_blank"
                    rel="noreferrer"
                    className="text-[#6B4226] font-bold hover:underline mt-0.5 block"
                  >
                    https://www.lekhoktripura.in/
                  </a>
                  <p className="text-[10px] text-stone-500 mt-1 font-medium">
                    Printed on header of each generated invoice for easy mobile scanning.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ACTION BUTTON BAR (White Cream Brown Theme) */}
      <div className="flex flex-wrap items-center justify-center gap-3.5 rounded-3xl border border-amber-900/15 bg-white p-6 shadow-xl shadow-stone-200/50">
        <button
          onClick={onGenerate}
          className="flex items-center gap-2 rounded-xl bg-[#6B4226] px-6 py-3.5 text-xs font-black text-white hover:bg-[#52331C] transition shadow-md uppercase tracking-wider"
        >
          <Eye className="h-4 w-4" /> Generate Invoice
        </button>
        <button
          onClick={onDownloadPDF}
          className="flex items-center gap-2 rounded-xl border border-amber-800/30 bg-amber-100 px-5 py-3.5 text-xs font-bold text-amber-950 hover:bg-amber-200 transition uppercase tracking-wider shadow-sm"
        >
          <Download className="h-4 w-4 text-[#8B5E3C]" /> Save / Download PDF
        </button>
        <button
          onClick={onPrint}
          className="flex items-center gap-2 rounded-xl border border-stone-300 bg-[#F7F3ED] px-5 py-3.5 text-xs font-bold text-stone-800 hover:bg-stone-200 transition uppercase tracking-wider shadow-sm"
        >
          <Printer className="h-4 w-4" /> Print
        </button>
        <button
          onClick={onSendEmail}
          className="flex items-center gap-2 rounded-xl border border-blue-300 bg-blue-50 px-5 py-3.5 text-xs font-bold text-blue-900 hover:bg-blue-100 transition uppercase tracking-wider"
        >
          <Mail className="h-4 w-4" /> Send Email
        </button>
        <button
          onClick={onSendWhatsApp}
          className="flex items-center gap-2 rounded-xl border border-emerald-300 bg-emerald-50 px-5 py-3.5 text-xs font-bold text-emerald-900 hover:bg-emerald-100 transition uppercase tracking-wider"
        >
          <MessageSquare className="h-4 w-4" /> Send WhatsApp
        </button>
        <button
          onClick={onReset}
          className="flex items-center gap-2 rounded-xl border border-rose-300 bg-rose-50 px-4 py-3.5 text-xs font-bold text-rose-900 hover:bg-rose-100 transition uppercase tracking-wider"
        >
          <RefreshCw className="h-4 w-4" /> Reset
        </button>
      </div>

      <p className="text-center text-[11px] text-stone-500 font-medium">
        Click SAVE / DOWNLOAD PDF — choose Save to PDF in the browser print window. | GSTIN: 16BMLPC9718D1Z2
      </p>
    </div>
  );
}
